import type { Metadata } from "next";
import "../globals.css";
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="bg-background dark:bg-backgroundDark min-h-[100vh] font-montserrat">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
